### ISSUE TITLE
Filter results by Not Archived

### ISSUE THREAD

**Issue by clintonyeb** [diptadas/flarn#36]
If an element is archived, it shouldn't be returned in results list, eg. getProblems

**Comment by diptadas** [comment]
@clintonyeb 
Removed archived for `getAll` and `getRandom`.
kept for `searchProblem`, should we also remove from there?

**Comment by clintonyeb** [comment]
Hmm I think we should remove for search too. The archived problems should be there to supply their id to other elements that depend on them but shouldn't be viewed on the UI. If it can be search, users will try to perform operations on it

**Comment by diptadas** [comment]
Implemented
